name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: nrwl/nx-set-shas@v3

      - name: Install Dependancies
        run: npm install && npm ci

      - name: Style Lint Check
        run: npx nx format:check

      - name: ESLint Check
        run: npx nx affected -t lint --parallel=3

      - name: Unit Tests
        run: npx nx affected -t test --parallel=3

      - name: Build
        run: npx nx affected -t build --parallel=3
